### ISSUE TITLE
Change fb0_framebuffer_num for mele  a1000 for better 3D acceleration

### ISSUE THREAD

**Issue by naguirre** [linux-sunxi/sunxi-boards#17]
Could it be possible add 
fb0_framebuffer_num = 3
in fex files of mela a1000 to enable 3D acceleration. As explained in xf86-video-fbturbo README.md
Other boards should be impacted by this change too.

If there is still a high CPU usage in Xorg server and the performance
   is poor for 3D graphics on Allwinner hardware, please make sure that
   the framebuffer size reservation is large enough to allocate memory
   for DRI2 buffers. The value fb0_framebuffer_num needs to be set at
   least to 3 in the fex file

What you think about that ?

**Comment by libv** [comment]
This should be part of the wiki, and people can go edit their fex files themselves. Plus, this is less and less relevant today, more than 5 years later :(
