### ISSUE TITLE
old Marsboard A20 sys_config.fex?

### ISSUE THREAD

**Issue by eseiker** [linux-sunxi/sunxi-boards#45]
https://gist.github.com/eseiker/814789141de860319753

I'm not sure this is needed in order to make device tree but I found it yesterday in SDK from the vendor, Haoyu Electronics. (http://www.haoyuelectronics.com/marsboard/marsboard-a20-md5sum-c668f869bc0b88c98d50f212bb7d28e6.tar.gz)
I don't know much about embedded systems so I just hope someone look into this. Thanks.

**Comment by libv** [comment]
Added to repo.
