### ISSUE TITLE
Parse error in a-star_kv49l.fex

### ISSUE THREAD

**Issue by n1tehawk** [linux-sunxi/sunxi-boards#51]
The lines in [a-star_kv49l.fex#L833-L851](https://github.com/linux-sunxi/sunxi-boards/blob/0e74463902e9c88be1bf310086b545deea3a6da8/sys_config/a33/a-star_kv49l.fex#L833-L851) contain `port:P@00`, which leads to a parse error in the FEX compiler. For now it's probably best to comment out these lines, just as was already done in the `[leds_para]` section.

EDIT: Just noticed that the [comment lines](https://github.com/linux-sunxi/sunxi-boards/blob/0e74463902e9c88be1bf310086b545deea3a6da8/sys_config/a33/a-star_kv49l.fex#L878-L882) in the `[leds_para]` section start with an invalid character. `\xEF\xBC\x9B` is a UTF-8 "full width semicolon", and needs to be replaced by a standard ASCII `\x3B`.

**Comment by libv** [comment]
Fixed.
